exec: ../PROJECT_NAME
args:
    - -e
    - prod
host: PRODUCTION_DOMAIN
static-hosts:
    - host: static.PRODUCTION_DOMAIN
      root: ../static
postgres: false
redirects:
    - from: beta.PRODUCTION_DOMAIN
      to: PRODUCTION_DOMAIN
    - from: www.PRODUCTION_DOMAIN
      to: PRODUCTION_DOMAIN